FROM node:18-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

# Копируем код
COPY . .

# Прямое использование esbuild
RUN npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist

# Команда запуска
CMD ["node", "dist/index.js"]
